architect:
  - iizudev
assets:
  crates-io.env: iizudev/.rultor#crates-io.env
install: |
  source /home/r/crates-io.env
release:
  script: |
    [[ "${tag}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]
    VERSION="${tag#v}"

    sed -i.bak "s/^version = .*/version = \"${VERSION}\"/" Cargo.toml && rm Cargo.toml.bak
    grep -q "version = \"${VERSION}\"" Cargo.toml

    git add Cargo.toml
    git commit -m "bump version to ${VERSION}" || echo "nothing to commit?"
    
    cargo test --lib
    cargo publish --token ${IIZUDEV_CRATES_IO_TOKEN}
