name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: cargo test --verbose
    - name: Publish
      run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
